from sqlalchemy import Column, Integer, String, Float, DateTime, LargeBinary
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func
from ..models import Base

class TrackModel(Base):
    __tablename__ = 'tracks'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    artist = Column(String)
    album = Column(String)
    track = Column(String)
    track_number = Column(Integer)
    genre = Column(String)
    subsonic_id = Column(String, unique=True)
    musicbrainz_artistid = Column(String)
    musicbrainz_albumid = Column(String)
    musicbrainz_trackid = Column(String)
    releasetype = Column(String)
    genre_embedding = Column(LargeBinary)
    mfcc_covariance = Column(LargeBinary)
    mfcc_mean = Column(LargeBinary)
    mfcc_temporal_variation = Column(Float)
    bpm = Column(Float)
    loudness = Column(Float)
    dynamic_complexity = Column(Float)
    energy_curve_mean = Column(Float)
    energy_curve_std = Column(Float)
    energy_curve_peak_count = Column(Integer)
    key_tonic = Column(String)
    key_scale = Column(String)
    key_confidence = Column(Float)
    chord_unique_chords = Column(Integer)
    chord_change_rate = Column(Float)
    vocal_pitch_presence_ratio = Column(Float)
    vocal_pitch_segment_count = Column(Integer)
    vocal_avg_pitch_duration = Column(Float)
    groove_beat_consistency = Column(Float)
    groove_danceability = Column(Float)
    groove_dnc_bpm = Column(Float)
    groove_syncopation = Column(Float)
    groove_tempo_stability = Column(Float)
    mood_aggressiveness = Column(Float)
    mood_happiness = Column(Float)
    mood_partiness = Column(Float)
    mood_relaxedness = Column(Float)
    mood_sadness = Column(Float)
    spectral_character_brightness = Column(Float)
    spectral_character_contrast_mean = Column(Float)
    spectral_character_valley_std = Column(Float)
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())
